package org.cirjson.serialization.internal

import org.cirjson.serialization.CircularKSerializer
import org.cirjson.serialization.InternalCircularSerializationApi

/**
 * An interface for a [CircularKSerializer] instance generated by the compiler plugin.
 *
 * Should not be implemented manually or used directly.
 */
@InternalCircularSerializationApi
public interface GeneratedCircularSerializer<T> : CircularKSerializer<T> {

    public fun childSerializers(): Array<CircularKSerializer<*>>

    public fun typeParametersSerializers(): Array<CircularKSerializer<*>> = EMPTY_SERIALIZER_ARRAY

}